=== JNM-2T17/SystemScape/clients/clientList.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT client_list (client)+>

<!ELEMENT client ( ( company_name | client_name ), project_name*, contact ) >

<!ENTITY % pc "(#PCDATA)">
<!ENTITY % cd "CDATA">

<!ELEMENT company_name %pc;>
<!ELEMENT client_name %pc;>

<!ELEMENT project_name %pc;>

<!ELEMENT contact (contact_person*)>

<!ELEMENT contact_person (name,contact_details*)>
<!ATTLIST contact_person position CDATA #implied>

<!ELEMENT name (#%cd;)>

<!ELEMENT contact_details %pc;>
<!ATTLIST contact_details type %cd; #required>

=== JNM-2T17/SystemScape/Top3Clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE client_list SYSTEM "clientList.dtd">
<?xml-stylesheet type="text/xsl" href="clientList.xsl"?>

<client_list>
	<client>
		<company_name>Torrent Pharmaceuticals Philippines</company_name>
		<contact>
			<contact_person position="marketing director">
				<name>Karmi Dungo</name>
				<contact_details type="mobile">(+63)9989672003</contact_details>
			</contact_person>
		</contact>
	</client>
	<client>
		<company_name>CAI-STA</company_name>
		<project_name>Inventory System for Purchases</project_name>
		<contact>
			<contact_person>
				<name>Rosalie Fernandez</name>
				<contact_details type="mobile">(+63)9175977209</contact_details>
				<contact_details type="e-mail">sally_fernandez@compaid.com</contact_details>
				<contact_details type="landline">(+02)581-91-24</contact_details>
			</contact_person>
		</contact>
	</client>
	<client>
		<company_name>Camella Homes</company_name>
		<project_name>Building Cost Estimator</project_name>
		<contact>
			<contact_person position="civil engineer">
				<name>Runar Quindoza</name>
				<contact_details type="e-mail">rcquindoza@gmail.com</contact_details>
			</contact_person>
		</contact>
	</client>
</client_list>
